// <auto-generated />
namespace ToDo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateToDoIndexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateToDoIndexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201407030346338_CreateToDoIndexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
